### ISSUE TITLE
What is 'feature_path' in input_generator.py ?

### ISSUE THREAD

**Issue by pranoothatwar** [jasonustc/V2S-tensorflow#1]
Hey, I couldn't figure out the significance of 'feature_path'?
Is it the extracted features from VGG or c3d for the dataset or is it something else ?

**Comment by jasonustc** [comment]
@pranoothatwar  Yes, the 'feature_path' is the folder path that you save your features that are extracted from VGG or C3D (like 'fc7-1' layer etc.) saved as .npz format.  You can refer to 'get_VGG' or 'get_c3d' in 'input_generator' for more details ~
